from core.errors import CustomError


class ValidationError(CustomError):
    pass
